security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }

        api_user:
            id: App\Security\Provider\SlackUserProvider

        slack_user:
            memory:
                users:
                    slack: { password: '', roles: ['ROLE_USER'] }

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        auth:
            pattern:
                - ^/api/auth/
            security: false
        slack:
            pattern: ^/api/slack/
            lazy: true
            provider: slack_user
            custom_authenticators:
                - App\Security\Authenticator\SignedSlackAuthenticator

        api:
            pattern: ^/api/
            lazy: false
            provider: api_user
            stateless: true
            access_token:
                token_handler:
                    oidc_user_info: https://slack.com/api/openid.connect.userInfo

    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
